想像上を操作
MLShukai/ami-vconf24 pull request #152
Opened 2024-09-25 15:22 UTC by myxyy

## 概要

https://github.com/MLShukai/ami-vconf24/issues/149

### 既知の問題
* outputフォルダが出力される

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-09-26 01:29 UTC, Geson-anko requested changes
@myxyy 実装ありがとうございます。大体できてきましたね。Keyboardが取れない問題はRemoteからアクセスしている場合に発生するかもしれません。`Moonlight`とかなら大丈夫だった気がしますが、keyboardの動作確認に関してはこちらでも試してみます。

2024-09-26 01:29 UTC, Geson-anko commented on pyproject.toml
> +keyboard = "^0.13.5"
`keyboard`モジュールの依存関係に関しては `play_imagination_world.py`のスクリプトの冒頭に記述してください。プロジェクト自体に依存関係を追加し続けると`poetry install`が時間がかかって大変になるので。
```suggestion
```

2024-09-26 01:29 UTC, Geson-anko commented on scripts/play_imagination_world.py
hydraやomegaconfは使わずに、ハイパラは全て決め打ちで `IJEPAEncoder`,  `IJEPALatentVisualizationDecoder`, `ForwardDynamicsActionReward`をインスタンス化してください。このスクリプトを汎用的に使いたい気持ちはありますが、かけられる工数的に書捨てのスクリプトコードのような実装でOKです。

hiddenの初期状態は `torch.zeros`で実装してください。
https://github.com/MLShukai/ami-vconf24/blob/main/configs/interaction/agent/curiosity_image_multi_step_imagination.yaml#L3-L9

2024-09-26 01:29 UTC, Geson-anko commented on scripts/play_imagination_world.py
> +    class KeyboardActionHandler:
classは関数の中ではなく、スクリプトの Global Fieldに書いてください。

2024-09-26 01:29 UTC, Geson-anko commented on scripts/play_imagination_world.py
> +        reconstruction = decoder(embedding.unsqueeze(0))
0 - 255の間へmin max normalizationをお願いします。
```suggestion
        reconstruction = decoder(embedding.unsqueeze(0))
        reconstruction = (reconstruction - reconstruction.min()) / (reconstruction.max() - reconstruction.min() + 1e-8) * 255
```

2024-09-26 01:29 UTC, Geson-anko commented on scripts/play_imagination_world.py
> +        cv2.imshow("imagination world", reconstruction.squeeze(0).permute(1,2,0).to("cpu").detach().numpy())
RGB 2 BGRをお願いします。また uint 8型への変更もお願いします。

2024-10-01 23:06 UTC, Geson-anko requested changes
@myxyy hydraやOmegaconfは一旦無しで実装お願いします．
余裕が出たら汎用化しますので

2024-10-01 23:06 UTC, Geson-anko commented on scripts/play_imagination_world.py
> +def main(cfg: DictConfig) -> None:
決め打ちでハイパラ書いていくのでhydraいらないと思います．
```suggestion
def main() -> None:
```

2024-10-01 23:06 UTC, Geson-anko commented on scripts/play_imagination_world.py
> +
パラメータのダウンロードリンクの記述お願いします．
```suggestion
# Parameter: https://drive.google.com/file/d/1saWq1fAbyA_BCZryUiWgPixJ6JCssLy0/view?usp=sharing
```

2024-10-02 13:12 UTC, myxyy commented on scripts/play_imagination_world.py
> +    initial_observation = torch.randn(
すみませんpush忘れでした
画像を読み込むようになってます

2024-10-02 13:19 UTC, myxyy commented on scripts/play_imagination_world.py
> +def main(cfg: DictConfig) -> None:
対応しました

2024-10-02 13:19 UTC, myxyy commented on scripts/play_imagination_world.py
> +
対応しました

2024-10-03 05:34 UTC, Geson-anko commented on pyproject.toml
> +keyboard = "^0.13.5"
そうですね． コメントで `# pip install keyboard`と付けておきましょう．

2024-10-03 05:59 UTC, Geson-anko approved these changes
動作確認しました．回転には機敏に反応しますね．
若干修正したので，それを確認したらMergeしてください．
https://github.com/MLShukai/ami-vconf24/pull/152/commits/18a707f17965b792c359561e0fb7b71dccc96195

2024-10-03 12:28 UTC, merged