ParallelScan版SioConv実装
MLShukai/ami-vconf24 pull request #178
Opened 2024-11-05 14:25 UTC by myxyy

## 概要

minGRUで使われているParallelScanを取り込んだSioConv
ヘッド毎の忘却が次元数に増えた

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-11-06 02:37 UTC, Geson-anko approved these changes
@myxyy Approveします。

2024-11-06 02:42 UTC, Geson-anko requested changes
@myxyy ヘッドがハイパラから消えたんですね。修正あるのでよろしくお願いします。

2024-11-06 02:42 UTC, Geson-anko commented on ami/models/components/sioconvps.py
> +import numpy as np
PSがParallel Scanであることを何かしらの形で記述してください。
```suggestion
# SioConv with Parallel Scan  (PS)
import numpy as np
```

2024-11-06 02:42 UTC, Geson-anko commented on ami/models/components/sioconvps.py
> +        self.is_refresh = True
これいらないです。
```suggestion
```

2024-11-06 12:19 UTC, myxyy commented on ami/models/components/sioconvps.py
> +import numpy as np
https://github.com/MLShukai/ami-vconf24/pull/178/commits/619fe7d605178c737a2247094706e5f009f3b907
対応しました

2024-11-06 12:19 UTC, myxyy commented on ami/models/components/sioconvps.py
> +        self.is_refresh = True
https://github.com/MLShukai/ami-vconf24/pull/178/commits/d04e856db4f1b54fecd2511c3e3db02d8e2fd0dc
対応しました

2024-11-07 05:26 UTC, Geson-anko approved these changes
@myxyy Approveします。

2024-11-07 12:18 UTC, merged