Feature/#37/i_jepa_model
MLShukai/ami-vconf24 pull request #45
Opened 2024-08-04 08:23 UTC by zassou65535

## 概要

I-JEPAのEncoderとPredictor(引用元: [I-JEPAの本家リポジトリ](https://github.com/facebookresearch/ijepa) )、それらのテストの追加

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-08-04 23:33 UTC, Geson-anko requested changes
@zassou65535 実装ありがとう。VisionTransformerEncoderやVisionTransformerPredictorという名前にするよりも、IJEPAEncoderや IJEPAPredictorという名前にする方が良いと思う。

2024-08-04 23:37 UTC, Geson-anko commented on ami/models/i_jepa.py
> +        x += select_patches_by_indices(x_positional_encodings, patch_selections_for_context_encoder)
```suggestion
```
latentsってすでに位置情報がエンコーディングされていると思うからいらないと思うんだけどな...

2024-08-05 01:21 UTC, Geson-anko commented on ami/models/i_jepa.py
> +                    nn.init.constant_(m.bias, 0)
ここモジュール関数として外に出してもいいかもね。
そんで、`functools.partial`を使って`init_std`を指定して渡す。
`self.apply(partial(_init_weights, init_std=0.02)`
```suggestion
def  _init_weights(m: nn.Module, init_std: float) -> None:
        match m:
            case nn.Linear():
                torch.nn.init.trunc_normal_(m.weight, std=self.init_std)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            case nn.LayerNorm():
                nn.init.constant_(m.bias, 0)
                nn.init.constant_(m.weight, 1.0)
            case nn.Conv2d():
                torch.nn.init.trunc_normal_(m.weight, std=self.init_std)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
```

2024-08-05 01:23 UTC, Geson-anko commented on ami/models/i_jepa.py
> +            rescale(layer.mlp.fc2.weight.data, layer_id)
ここもモジュール関数に展開していいと思う。
```suggestion
def fix_init_weight(vit_layers: Sequence[VisionTransformerLayer]) -> None:
        def rescale(param: torch.Tensor, layer_id: int) -> None:
            param.div_(math.sqrt(2.0 * layer_id))

        for layer_id, layer in enumerate(vit_layers, start=1):
            rescale(layer.attn.proj.weight.data, layer_id)
            rescale(layer.mlp.fc2.weight.data, layer_id)
```

2024-08-05 03:34 UTC, zassou65535 commented on ami/models/i_jepa.py
> +        x = x + positional_encodings
https://github.com/MLShukai/ami-vconf24/pull/45/commits/f0446904ed920130dc5f9f49a99d61241172400b で解消

2024-08-05 05:03 UTC, Geson-anko approved these changes
@zassou65535 approveします。

2024-08-05 05:04 UTC, merged