SideChannelでUnity側から位置情報送信
MLShukai/ami-vconf24 pull request #55
Opened 2024-08-10 07:04 UTC by myxyy

## 概要

https://github.com/MLShukai/AMIUnityEnvironment/pull/4 が必要

mypyでエラーが出ている、要対応
```
ami/interactions/environments/unity_environment.py:18: error: Class cannot subclass "SideChannel" (has type "Any")  [misc]
```

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-08-10 11:18 UTC, Geson-anko requested changes
@myxyy 実装ありがとうございます。修正あるので対応お願いいたします。

2024-08-10 11:18 UTC, Geson-anko commented on configs/interaction/environment/unity.yaml
> +log_file_path: ???
デフォルト値`None`でお願いします。
```suggestion
log_file_path: null
```

2024-08-10 11:18 UTC, Geson-anko commented on ami/interactions/environments/unity_environment.py
> +
csvヘッダ書き込んでください。
```suggestion
        with open(self.log_file_path, "w") as f:
            f.write("frame_count, position_x, position_y, position_z, euler_x, euler_y, euler_z\n")
```

2024-08-10 11:18 UTC, Geson-anko commented on ami/interactions/environments/unity_environment.py
> +            transform_log_channel = TransformLogChannel(UUID("621f0a70-4f87-11ea-a6bf-784f4387d1f7"), log_file_path)
このように記述すると簡潔です。
```suggestion
        side_channels = [self.engine_configuration_channel]
        if log_file_path is not None:
            transform_log_channel = TransformLogChannel(UUID("621f0a70-4f87-11ea-a6bf-784f4387d1f7"), log_file_path)
            side_channels.append(transform_log_channel)
```

2024-08-10 11:18 UTC, Geson-anko commented on ami/interactions/environments/unity_environment.py
> +                else [self.engine_configuration_channel],
先のコメントに付随します。
```suggestion
                side_channels=side_channels
```

2024-08-10 11:18 UTC, Geson-anko commented on configs/experiment/unity_sioconv.yaml
> +    log_file_path: ${paths.output_dir}/unity.csv
わかりやすい名前にしましょう。
```suggestion
    log_file_path: ${paths.output_dir}/unity_infomation_logs.csv
```

2024-08-10 12:23 UTC, myxyy commented on configs/interaction/environment/unity.yaml
> +log_file_path: ???
https://github.com/MLShukai/ami-vconf24/pull/55/commits/b359ff15036cd281c15d3e2286fc2098b8f9a035
修正しました

2024-08-10 12:23 UTC, myxyy commented on ami/interactions/environments/unity_environment.py
> +
https://github.com/MLShukai/ami-vconf24/pull/55/commits/50f5b862c198b2dc137a9d9f82ac9e126da05b85
修正しました

2024-08-10 12:24 UTC, myxyy commented on ami/interactions/environments/unity_environment.py
> +            transform_log_channel = TransformLogChannel(UUID("621f0a70-4f87-11ea-a6bf-784f4387d1f7"), log_file_path)
https://github.com/MLShukai/ami-vconf24/pull/55/commits/6183576f12a0374656579fd6cd4fcc00e7a00500
対応しました

2024-08-10 12:24 UTC, myxyy commented on ami/interactions/environments/unity_environment.py
> +                else [self.engine_configuration_channel],
https://github.com/MLShukai/ami-vconf24/pull/55/commits/6183576f12a0374656579fd6cd4fcc00e7a00500
対応しました

2024-08-10 12:24 UTC, myxyy commented on configs/experiment/unity_sioconv.yaml
> +    log_file_path: ${paths.output_dir}/unity.csv
https://github.com/MLShukai/ami-vconf24/pull/55/commits/699c1f6534184224cd57c74c7e0a713eb8fe8059
修正しました

2024-08-11 06:29 UTC, Geson-anko approved these changes

2024-08-11 06:30 UTC, Geson-anko commented
Approveしました

2024-08-11 10:27 UTC, merged