Latent visualization decoder
MLShukai/ami-vconf24 pull request #85
Opened 2024-08-25 13:05 UTC by zassou65535

## 概要

SSLモデルからの出力空間を画像として可視化するモデル`LatentVisualizationDecoder`の追加
参考: https://github.com/CompVis/stable-diffusion/blob/main/ldm/modules/diffusionmodules/model.py#L462

## 変更内容

`LatentVisualizationDecoder`に加え、それらの構成要素の`ResBlock`クラスと`DecoderBlock`を含む。
上記の3つに対するテストも追加している。

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-08-26 01:39 UTC, Geson-anko requested changes
@zassou65535 実装ありがとう。出力サイズを任意に指定できる機能を実装してくれるととても助かる。

2024-08-26 01:39 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +# Ref: https://github.com/facebookresearch/ijepa
コピペの残り？

```suggestion
```

2024-08-26 01:39 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        """Apply the block to input Tensor, conditioned on emb.
コピペミス？
```suggestion
        """Apply the block to input Tensor.
```

2024-08-26 01:39 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        )
直接Iterableとして渡して良い。
```suggestion
        self.decoder_blocks = nn.Sequential(
            DecoderBlock(
                in_channels=blocks_in_channels,
                out_channels=blocks_out_channels,
                n_res_blocks=n_res_blocks,
                use_upsample=(not (i == (len(decoder_blocks_in_and_out_channels) - 1))),
            )
            for i, (blocks_in_channels, blocks_out_channels) in enumerate(decoder_blocks_in_and_out_channels)
        )
```

2024-08-26 01:39 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
機能要望。出力サイズを任意に指定できるようにしてほしい。
[`torchvision.transforms.functional.center_crop`](https://pytorch.org/vision/main/generated/torchvision.transforms.functional.center_crop.html)を用いて実装すると楽だと思う。
Convolutionによって出力される推定画像サイズが output sizeよりも下回っていた場合は Assertionエラーを出すと良いと思う。
```suggestion
        num_heads: int,
        output_size: size_2d
```

2024-08-26 06:55 UTC, zassou65535 commented on ami/models/latent_visualization_decoder.py
> +        )
これだけど、suggestionしてくれた記法ではエラーになるっぽかったから修正前のままにしておきたい
```
FAILED tests/models/test_latent_visualization_decoder.py::TestLatentVisualizationDecoder::test_latent_visualization_decoder[4-4-3-decoder_blocks_in_and_out_channels1-384-1-1] - TypeError: LatentVisualizationDecoder.__init__.<locals>.<genexpr> is not a Module subclass
```

2024-08-26 10:34 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
@zassou65535 
> LatentVisualizationDecoderの__init__の引数として、「元の入力(n_patches_height, n_patches_width)を2の何乗倍したいか」を渡す

これはやってもやらなくてもいいかな。出力サイズが直感的に推定できるのは良いと思うから、やっていいとは思う。


> 「出力Tensorのサイズを任意に設定できます！！」からの「実は出力をcropしてるだけでした」って実装あんまり良くない気がする
> → ネットワークの構造に全く依存しない箇所で無理やり出力を決めてしまっている所があまり良くない気がした

別に問題ないと思う。`output_size`っていうのが、Convolutionを組み合わせて導かれるような意図を持ってしまうなら、確かに問題にはなり得るけど、Convolutionで指定よりも大きなサイズまでUpsamplingした上で、Cropするという意図が明確に伝わるコードであれば、全く問題にならないと思う。
あと出力をただCropするだけだからハイパラに影響があるとは考えられないな。

 `output_size`はデフォルトNoneにして置いて、設定されている時だけその処理を実行するっていうのが良いかもね。

2024-08-26 10:36 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
> 入力patch(batch_size, n_patches, dims)に対してtorch.meanを実行

これは避けたいな... I-JEPAは可視化に関してあまり詳細に追及していないので、信頼しきれない。

2024-08-26 11:08 UTC, zassou65535 commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
ごめんちょっと質問がずれるんだけど、出力画像のサイズって任意で指定できなきゃダメ？`assert 2の累乗かどうか(output_size)`みたいに、例えば2の倍数のみ指定可能みたいな制約ってつけたらまずい？

2024-08-26 23:36 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
@zassou65535 このモジュール自体にその機能を実装する必要はないと思う。結局画像の再構成誤差を取る際に 144x144の形に直さないといけないと思うから、それが問題なく実装できればなんでも良いと思う。ただ、Trainerで任意の画像サイズにCropしたりする処理を書くのはお勧めできないな。出力サイズのプロパティは常にモデルが持つものなので、そこで設定できるようにするのが良い。`nn.Sequential`で、CenterCropをするレイヤーと結合しても良いかもね。

2024-08-27 05:55 UTC, zassou65535 commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
どっちかっていうと必要不必要というよりは、この制約があった方がモデルの実装が単純化できそうという意図があって聞いてみた感じだった
あと、出力画像って絶対I-JEPAへの入力サイズと同一じゃなきゃだめ？I-JEPAへの入力は144x144だけど、Decoderからの出力は128x128ですとかはダメ？

2024-08-27 06:04 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
@zassou65535 その発想はなかった。ターゲット画像をモデルの出力画像のサイズに合わせてリサイズするってことね。

まあそれなら良いと思う。Approveするよ。

2024-08-27 06:05 UTC, Geson-anko approved these changes
@zassou65535 実装ありがとう。Approveする。

2024-08-27 06:11 UTC, zassou65535 commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
OKじゃあその方針で実装しよう　Approveしてもらった後でアレなんだけど、これに関して一回実装を少し改良するからその時はもう1度レビューしてもらってもいい？

2024-08-28 05:54 UTC, Geson-anko commented on ami/models/latent_visualization_decoder.py
> +        num_heads: int,
@zassou65535 金曜あたりまでに TrainerのPR出せるならOK. 
もし単に実装を綺麗にしたいというエンジニアのエゴ的なものなら程々に。すでに要件は満たしているからね。

2024-08-31 10:30 UTC, merged